config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'issues#index'

  resources :issues, except: %i[index show]
  get '/:status', to: 'issues#index', as: :issues_status
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/issue.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: issues
#
#  id            :bigint           not null, primary key
#  airbrake_link :string           not null
#  resolved_at   :datetime
#  shipped_at    :datetime
#  status        :integer          default("not_started"), not null
#  trello_link   :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class Issue < ApplicationRecord
  enum status: {
    not_started: 0,
    in_progress: 1,
    testing: 2,
    accepted: 3,
    archived: 4
  }

  validates :airbrake_link, :status, presence: true

  scope :by_trello_link, ->(value) { where('trello_link ILIKE ?', "%#{value}%") }
  scope :by_airbrake_link, ->(value) { where('airbrake_link ILIKE ?', "%#{value}%") }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/issues_controller.rb
# frozen_string_literal: true

class IssuesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_issue, only: %i[destroy edit update]

  has_scope :trello_link, allow_blank: true do |_controller, scope, value|
    scope.by_trello_link(value)
  end

  has_scope :airbrake_link, allow_blank: true do |_controller, scope, value|
    scope.by_airbrake_link(value)
  end

  def create
    @issue = Issue.new(issue_params)

    if @issue.save
      redirect_to :root
    else
      render :new
    end
  end

  def destroy
    @issue.destroy

    redirect_to :root
  end

  def edit; end

  def index
    return redirect_to(:root) if unaccaptable_status?

    @facade = IssuesFacade.new(apply_scopes(Issue.all), params)
  end

  def new
    @issue = Issue.new
  end

  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to :root }
        format.json { render json: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors }
      end
    end
  end

  private

  def issue_params
    params.require(:issue).permit(
      :airbrake_link,
      :resolved_at,
      :shipped_at,
      :status,
      :trello_link
    )
  end

  def set_issue
    @issue = Issue.find(params[:id])
  end

  def unaccaptable_status?
    params.key?(:status) && Issue.statuses.keys.exclude?(params[:status])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/issues/_issue.html.erb
<div class="issue-card">
  <%= turbo_frame_tag dom_id(issue) do %>
    <div class="issue-card-header">
      <%= render Issues::Status::Component.new(issue: issue) %>

      <div class="issue-actions">
        <%= link_to edit_issue_path(issue) do %>
          <%= image_tag 'icons/pencil.svg' %>
        <% end %>

        <%= link_to issue_path(issue), method: :delete, data: { confirm: 'Are you sure?' } do %>
          <%= image_tag 'icons/trash.svg' %>
        <% end %>
      </div>
    </div>

    <div class="issue-card-body">
      <p class="issue-information">
        Shipped at:
        <strong><%= issue.shipped_at ? issue.shipped_at.strftime('%B %e, %Y') : '-' %></strong>
      </p>
      <p class="issue-information">
        Resolved at:
        <strong><%= issue.resolved_at ? issue.resolved_at.strftime('%B %e, %Y') : '-' %></strong>
      </p>
    </div>

    <div class="issue-card-footer">
      Go to:
      <%= link_to 'Airbrake', issue.airbrake_link, data: { turbo: false } %>,
      <%= link_to 'Trello', issue.trello_link, data: { turbo: false } %>
    </div>
  <% end %>
</div>

app/views/issues/edit.html.erb
<main class="container">
  <header class="section-header">
    <h1>Edit Issue</h1>
  </header>

  <%= turbo_frame_tag dom_id(@issue) do %>
    <%= render Issues::IssueForm::Component.new(issue: @issue) %>
  <% end %>
</main>

app/views/issues/index.html.erb
<main class="container">
  <header class="section-header">
    <h1><%= @facade.status&.humanize %> Issues (<%= @facade.total_amount %>)</h1>

    <div class="issues-actions">
      <%= link_to '+ Add New Issue', new_issue_path, class: 'button button-primary' %>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'button button-accent' %>
    </div>
  </header>

  <div class="issues-status-navigation">
    <% if @facade.status_page? %>
      <%= link_to 'All', root_path %>
    <% else %>
      <strong>All</strong>
    <% end %>

    <% Issue.statuses.each_key do |status| %>
      <% if @facade.status == status %>
        <strong><%= status.humanize %></strong>
      <% else %>
        <%= link_to status.humanize, issues_status_path(status) %>
      <% end %>
    <% end %>
  </div>

  <div class="issues-filters form-wrapper">
    <%= form_tag @facade.current_path, method: :get do %>
      <div class="form-field">
        <%= label_tag :airbrake_link %>
        <%= text_field_tag :airbrake_link, params[:airbrake_link] %>
      </div>

      <div class="form-field">
        <%= label_tag :trello_link %>
        <%= text_field_tag :trello_link, params[:trello_link] %>
      </div>

      <div class="form-actions">
        <%= submit_tag 'Search', class: 'button button-primary', name: nil %>
        <%= link_to 'Clear', @facade.current_path, class: 'button button-secondary clear-search-inputs' %>
      </div>
    <% end %>
  </div>

  <div class="issues-list">
    <%= render @facade.collection %>
  </div>

  <div class="issues-pagination">
    <%= paginate @facade.collection %>
  </div>
</main>

app/views/issues/new.html.erb
<main class="container">
  <header class="section-header">
    <h1>New Issue</h1>
  </header>

  <%= turbo_frame_tag dom_id(@issue) do %>
    <%= render Issues::IssueForm::Component.new(issue: @issue) %>
  <% end %>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbrakeDance</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css2?family=Commissioner:wght@400;600&display=swap" rel="stylesheet">

    <%= turbo_include_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>